### ISSUE TITLE
typo in configuration parameter name provided to vault?

### ISSUE THREAD

**Issue by absynth76** [redhat-cop/vault-config-operator#10]
At this location:

https://github.com/redhat-cop/vault-config-operator/blob/3077a7f1694483ece6032a8c54b51827237401ab/api/v1alpha1/kubernetesauthengineconfig_types.go#L169

the payload is filled with a parameter called kubernetes_ca_host, it should be kubernetes_ca_cert

consequently there is an error when creating the KubernetesAuthEngineConfig:
```
"message": "Error making API request.\n\nURL: PUT https://myvault.local/v1/auth/kubeauth/myconfig/config \nCode: 400. Errors:\n\n* one of pem_keys or kubernetes_ca_cert must be set"
```

Is it possible that part was never tested ?

**Comment by raffaelespazzoli** [comment]
this path was (manually) tested. Not sure how this bug slipped in. Anyhow, a PR to fix it is on the way.
