### ISSUE TITLE
Resource deletion stalls and is not propagated to Vault

### ISSUE THREAD

**Issue by davoustp** [redhat-cop/vault-config-operator#126]
Hi,

Using a Vault with kv-v2 enabled, creating a `RandomSecret` does properly create the entry into the Vault kv store.

However, removing the `RandomSecret` resource stalls after acknowledgment, and the Vault entry is not removed.

This is due to the fact that the finalizer key on the `RandomSecret` object is never removed - so Kubernetes awaits forever.
Manually removing the finalizer obviously unlocks the Kubernetes situation, but the Vault entry is left alone and still exists.

As far as I can tell, it does not look normal as the removal should be performed onto Vault as well.

By tracing calls to the `RandomSecretReconciler` controller, it turns out that the controller is not invoked upon the CR update on deletion: per https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/#how-finalizers-work, the deletion operation adds the deletionTimestamp (updating the CR object), then the Kube control plane awaits that the finalizer list is empty before actually removing the object.

Updating the `RandomSecret` CR is also entirely ignored - controller is not invoked, and no change is performed in Vault.

Note that this actually happens for any Custom Resource - removing an entire namespace containing multiple CRs from this operator hangs, Kubernetes reporting them as awaiting for finalizers.

This situation happens running a Kubernetes cluster 1.24.8 (GKE) with `vault-config-operator` version 0.8.10 deployed using Helm.

Is there anything I missed during deployment or configuration?
Thanks in advance,
Regards

**Comment by raffaelespazzoli** [comment]
there have been recent changes around that behavior. Let me test.

**Comment by davoustp** [comment]
Sure. Let me know if you need some more details or want me to test sthg.

**Comment by davoustp** [comment]
I looked into the code a bit more and think I found the root cause.


### Problem 1: the predicate used in `SetupWithManager` ignores the deletion-with-a-finalizer code flow

The code at https://github.com/redhat-cop/vault-config-operator/blob/main/controllers/randomsecret_controller.go#L159 registers the controller with a predicate, so that it's invoked only when applicable, which makes sense.
However, as described in https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/#how-finalizers-work, the kube client object deletion is actually an `event.UpdateEvent` for the Custom Resource updated with the new field `metadata.deletionTimestamp`.
Because of the way the predicate is built, it actually discards the triggered event and the reconcile function is not invoked.

### Problem 2: the reconciler function exits *before* checking if this is a deletion case

There is an early condition check which exits when the secret has already been created and no secret refresh is required at https://github.com/redhat-cop/vault-config-operator/blob/main/controllers/randomsecret_controller.go#L80
However, the code detecting and handling the deletion is performed a few line down at https://github.com/redhat-cop/vault-config-operator/blob/main/controllers/randomsecret_controller.go#L90 and never gets a chance to execute.

I can confirm that fixing those two issues does fix the problem: no more hanging, and the secret is deleted from Vault as expected.

**Comment by raffaelespazzoli** [comment]
do you want to send a PR?

**Comment by davoustp** [comment]
Hi @raffaelespazzoli 
Sorry I missed your question - I'll think about a PR next time.
Thanks for the fix, this is very close to what I did to confirm.
