### ISSUE TITLE
Move local development setup off paid registries?

### ISSUE THREAD

**Issue by ameyp** [redhat-cop/vault-config-operator#140]
I've been trying to get Tilt up and running, but I don't have a `quay.io` account or a RedHat account, and there are several private images used by tilt that are either on `quay.io` or on `registry.connect.redhat.com` or on `registry.access.redhat.com`.

**Comment by raffaelespazzoli** [comment]
this surprises me, can you list which images you cannot pull?

**Comment by ameyp** [comment]
- registry.connect.redhat.com/hashicorp/vault-k8s:1.2.0-ubi
- registry.connect.redhat.com/hashicorp/vault:1.12.3-ubi

Now that I've listed them out, I guess there's just two, not several. Technically not needed after all if I already have vault installed, initialized and unsealed on a test cluster.

And I was mistaken about `quay.io`, https://quay.io/plans/ doesn't list a free plan directly, but the FAQs state that it can be used for free with public repositories.

**Comment by ameyp** [comment]
I think I was wrong about the remaining two as well, feel free to close this if the following holds:

My main cluster runs `k3s`, so I was trying to get the local development setup working with a test cluster running on `kind`, and that couldn't pull images from the redhat registry. After struggling and failing, I caved and installed [crc](https://crc.dev) and it looks like the OpenShift cluster is able to pull from that registry just fine.

**Comment by ameyp** [comment]
Without logging in to quay.io, `vault-config-operator-controller-manager` fails for me at step 5:

```
STEP 5/5: ENTRYPOINT ["/manager"]
COMMIT quay.io/ameypar/vault-config-operator:tilt-build-1682040665
--> 6a7fa8be2d5d
Successfully tagged quay.io/ameypar/vault-config-operator:tilt-build-1682040665
6a7fa8be2d5d224030ce1fa6cb92a769d3569c84647b21d680cbd0854eeba489
Getting image source signatures
Copying blob sha256:de08479e7f476625de9e1587ec6e1884e8e8d71595fb06b32b3e3465d1ea09d4
Copying blob sha256:55ea6d5a354edb8a6eeeadb772359359f82959156d04193d5a7b2d79c827d9ee
Error: writing blob: initiating layer upload to /v2/ameypar/vault-config-operator/blobs/uploads/ in quay.io: unauthorized: access to the requested resource is not authorized
podman build -t $EXPECTED_REF --ignorefile ci.Dockerfile.dockerignore -f ./ci.Dockerfile .  && podman push $EXPECTED_REF $EXPECTED_REF exited with exit code 125

Build Failed: Custom build "podman build -t $EXPECTED_REF --ignorefile ci.Dockerfile.dockerignore -f ./ci.Dockerfile .  && podman push $EXPECTED_REF $EXPECTED_REF" failed: exit status 125
```

Are you sure it works for you without logging in? Could you confirm this by re-running Tilt from scratch after `docker logout quay.io`?

**Comment by eye0fra** [comment]
At this stage, you must be logged in, because you are sending the operator image to Quay.io for use during deployment.

**Comment by ameyp** [comment]
That's the part that's failing. If I login, it passes.
