### ISSUE TITLE
ServiceMonitor's serverName is wrong when not in the default namespace

### ISSUE THREAD

**Issue by John2020-cyber** [redhat-cop/vault-config-operator#159]
Hi,

I have deployed vault-config-operator via helm charts on OpenShift in a different namespace other than 'vault-config-operator'
the ServiceMonitor serverName doesn't change whereas Service picks up the name.

The ServiceMonitor gets the wrong serverName :

```
        serverName: >-
          vault-config-operator-controller-manager-metrics-service.vault-config-operator.svc
```

**Comment by raffaelespazzoli** [comment]
yes. this is an issue with OLM. There isn't much we can do. Either install in the default namespace or if you need to install in a different namespace use the helm chart.
