### ISSUE TITLE
Huge number of Vault leases in a specific timeframe once every day

### ISSUE THREAD

**Issue by glisav** [redhat-cop/vault-config-operator#160]
Hi Team,

We have identified a concerning trend in our Vault system where an unusually large number of leases are being generated on a daily basis, but only during a specific timeframe. This issue has raised concerns about the performance and stability of the system during this particular period.

Under normal circumstances, we expect a relatively consistent number of Vault leases to be generated throughout the day. However, during this specific timeframe, the number of leases generated is significantly higher than usual.

During the specified timeframe, there is a significant surge in the number of Vault leases generated compared to other periods. This sudden increase in volume has started to impact the system's performance, causing delays and potential instability.

We have been monitoring metrics from Vault and have seen the following:

- **vault_token_creation** - increased on the same timeframe
- **vault_expire_revoke** - decreased on the same timeframe
- **vault_expire_revoke_by_token** - decreased on the same timeframe
- **vault_expire_lease_expiration** - increased on the same timeframe

![image](https://github.com/redhat-cop/vault-config-operator/assets/22434655/0b78fe79-5c81-4daf-bd2f-909ffbe3c6e6)

From the Logging Platform, we have been checking the logs for this timeframe and most of the requests against Vault are from the path _auth/cluster-admin/login_, which is the CR used by VCO.

Environment:

Vault version: 1.12.3 (OSS)
Vault Config Operator: 0.8.13
Deployment: OpenShift

Can you please help me identify if this is by design or something is going wrong in here?
Thanks!

**Comment by glisav** [comment]
Hi,
Another observation related with this, is that after deleting the pod vault-config-operator-controller-manager, we saw a significant drop in the metric: _vault_expire_num_leases_


![image](https://github.com/redhat-cop/vault-config-operator/assets/22434655/83c57843-8e31-474b-87ed-08ebde3ecb3c)

We have deleted four times the pod, and each of the drops in the picture correspond with deletion moment.

**Comment by erlisb** [comment]
Hi @raffaelespazzoli, we are experiencing this in our OCP Cluster also.
Do you have a suggestion ?

**Comment by raffaelespazzoli** [comment]
hello, every reconcile cycle should generate a new token. The token and the connection context is lost after the reconcile cycle. I'd expect vault to remove the lease relative to that token by itself after its end of life. There is no token-renew logic in the code.
I am not sure why all the work seems to be done at the same time, but here is some speculation:
when the controller pod starts a reconcile cycle is started for every vault resources. So all the lease creation happen more or less at the same time. from then on the operator periodically runs the refresh cycle (every 6 hours?). And again all the request happen at the same time.
I am not familiar enough with vault to understand those metrics. Also I don't have a good hypothesis on why killing a pod causes a drop in the `vault_expire_num_leases`.
On observation before measuring these kinds of performance, make sure that the operator is not constantly looping on some resources, We had some issues like that before.
Also would it help if at the end of the reconcile cycle the operator were to explicitly revoke the lease?

**Comment by erlisb** [comment]
Hi @raffaelespazzoli, 

"On observation before measuring these kinds of performance, make sure that the operator is not constantly looping on some resources" -> I am not sure how we can check this.
"Also would it help if at the end of the reconcile cycle the operator were to explicitly revoke the lease?"--> If this would fix this issue, then yes.

We are currently experiencing spikes in cpu/memory, whenever the `vault_expire_num_leases ` happens, which leads to pod restarts, due to OOM issues.

If anyone else has experienced the same issue, and found a fix for it, please let us know.

**Comment by erlisb** [comment]
@raffaelespazzoli hi, we are into it. I will provide a feedback asap.Thx

**Comment by erlisb** [comment]
Hi @raffaelespazzoli, with the latest release of VCO v0.8.23, this issue seems to be fixed.
We don't notice the same behaviour in our prod environment : 

![image](https://github.com/redhat-cop/vault-config-operator/assets/40136986/5bae2ec7-cf23-41f2-a194-bf680e9c1bc9)

Thank you.

**Comment by glisav** [comment]
Hi @erlisb 
I can confirm that. With the latest release of Vault Config Operator, I can see that this issue is fixed.
Thank you!
