### ISSUE TITLE
In KubeAuthEngineConfig TokenReviewerServiceAccount shouldn't be optional and left empty ?

### ISSUE THREAD

**Issue by vhurtevent** [redhat-cop/vault-config-operator#176]
Hello,

we are testing vault-config-operator to bootstrap our Kubernetes clusters into Vault.
We are using  AuthEngineMount and KubernetesAuthEngineConfig resources to do that. The Vault objects are well created but our tests to authenticate Kubernetes serviceAccounts on the correct Vault login endpoints failed with `Permission denied`.

We checked several times the configuration (API URL, CACert, etc) and it's all ok.

In Vault if we just open the configuration edition form, and without modifying any values and just validating the form, the following authentication succeeded.

So we checked the KubernetesAuthEngineConfig ressources and we noticed this in the spec : 

```
spec:
  tokenReviewerServiceAccount:
    name: default
```

We don't want to work with a tokenReviewerServiceAccount, we want that the final vault client (serviceAccount from our Kubernetes applications) uses its own JWT to review its own token, As it's explained in the CRD file : ` If not set, the JWT submitted in the login payload will be used to access the Kubernetes TokenReview API.`
But vault-config-operator seems to always add this unwanted default values through the validating webhook.

How could I disable or change this behaviour ?

I tried a custom build removing the kubebuilder directives in kubernetesauthengineconfig_types.go to set tokenReviewerServiceAccount as optional but I get a pretty error in getJWTToken : 

```
redhat.io", "controllerKind": "KubernetesAuthEngineConfig", "KubernetesAuthEngineConfig": {"name":"pegase2","namespace":"vault-config-operator"}, "namespace": "vault-config-operator", "name": "pegase2", "reconcileID": "c782a392-9d7b-4b81-ae51-0e4da7c927f3"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x166f205]

goroutine 995 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x186bd40, 0x2a4c3c0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/redhat-cop/vault-config-operator/api/v1alpha1.(*KubernetesAuthEngineConfig).getJWTToken(0x1d64248?, {0x1d64248?, 0xc001733f50?})
	/workspace/api/v1alpha1/kubernetesauthengineconfig_types.go:92 +0x25
github.com/redhat-cop/vault-config-operator/api/v1alpha1.(*KubernetesAuthEngineConfig). (0xc000280780, {0x1d64248, 0xc001733f50}, {0x0?, 0x0?})
	/workspace/api/v1alpha1/kubernetesauthengineconfig_types.go:81 +0x7c
github.com/redhat-cop/vault-config-operator/controllers/vaultresourcecontroller.(*VaultResource).manageReconcileLogic(0xc000ef3c28, {0x1d64248, 0xc001733f50}, {0x1d78680?, 0xc000280780?})
	/workspace/controllers/vaultresourcecontroller/vaultresourcereconciler.go:93 +0xb6
github.com/redhat-cop/vault-config-operator/controllers/vaultresourcecontroller.(*VaultResource).Reconcile(0xc000ef3c28, {0x1d64248, 0xc001733f50}, {0x1d78680?, 0xc000280780})
	/workspace/controllers/vaultresourcecontroller/vaultresourcereconciler.go:65 +0x505
github.com/redhat-cop/vault-config-operator/controllers.(*KubernetesAuthEngineConfigReconciler).Reconcile(0xc000350d20, {0x1d64248, 0xc000bd1f20}, {{{0xc0011ca468?, 0x10?}, {0xc000549f60?, 0x40dae7?}}})
	/workspace/controllers/kubernetesauthengineconfig_controller.go:83 +0x3db
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1d641a0?, {0x1d64248?, 0xc000bd1f20?}, {{{0xc0011ca468?, 0x19ba2e0?}, {0xc000549f60?, 0x4045d4?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00027b2c0, {0x1d641a0, 0xc00073fb00}, {0x18d3da0?, 0xc0011c26e0?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00027b2c0, {0x1d641a0, 0xc00073fb00})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x333
```

As I understand PrepareInternalValues and getJWTToken are not coded to support a configuration without TokenReviewerServiceAccount.

Could someone help me ?

**Comment by raffaelespazzoli** [comment]
when you login to vault using your application service account (as you wish to do), Vault calls the tokenreview service in kubernetes to verify that the passed service account token is valid. The tokenreview service is an authenticated service, so you need some credentials to authenticate there. The authenticated identity needs permission to call the token review service, obvious. 
You needs a different service account for this call and it's going to be the same for every login.
All of this has little to do with this operator and it's really about teh inner working of the kubernetes auth engine. It is explained in detail here: https://developer.hashicorp.com/vault/docs/auth/kubernetes#configuring-kubernetes

**Comment by vhurtevent** [comment]
Hello @raffaelespazzoli,

you don't need a different service account for the TokenReview call. It's explained there : https://developer.hashicorp.com/vault/docs/auth/kubernetes#use-the-vault-client-s-jwt-as-the-reviewer-jwt

We still need to grant sufficient permissions (system-delegator) to all Vault client's ServiceAccounts, though.

My understanding : despite the description in the CRD : https://github.com/redhat-cop/vault-config-operator/blob/main/config/crd/bases/redhatcop.redhat.io_kubernetesauthengineconfigs.yaml#L169

```
TokenReviewerServiceAccount A service account JWT used
to access the TokenReview API to validate other JWTs during login.
If not set, the JWT submitted in the login payload will be used
to access the Kubernetes TokenReview API.
```

Vaut-config-operator asks the TokenReviewerServiceAccount to be mandatory, and if not set, force the name to  `default`.

I am no expert but I thought that : 
- change the TokenReviewerServiceAccount from mandatory to optional
- disable the default to `name: default`
- Condition the function PrepareInternalValues based on the presence or absence of TokenReviewerServiceAccount

I can try to provide a PR if you think it's valuable.

**Comment by vhurtevent** [comment]
The PR is working correctly in my opinion, TokenReviewerServiceToken can now be omit in KubeAuthEngineConfig spec and the AuthEngine in Vault is correctly configured without token_reviewer_jwt making Vault clients asking TokenReview for itself possible.
