### ISSUE TITLE
RandomSecret does not work when using kv store v2

### ISSUE THREAD

**Issue by jfroment** [redhat-cop/vault-config-operator#22]
Hello,

I tried to create a ``RandomSecret`` by following the provided examples, the only difference is that I used a kv store in v2 format (created with the ``SecretEngineMount`` CRD by passing the "options.version" field to create a v2 kv).
But then the Operator could not put data, as I had the following error:

```
Code: 400. Errors:

* no data provided
```

Trying with a v1 KV worked.

I think it might be the same issue as https://github.com/hashicorp/vault/issues/6200 which is basically the way the kv v2 handles path (using a ``data`` map), as opposed to v1.

**Comment by raffaelespazzoli** [comment]
closed by #26
