### ISSUE TITLE
Custom resource cannot be deleted if it fails to be created

### ISSUE THREAD

**Issue by bukovjanmic** [redhat-cop/vault-config-operator#23]
If a custom resource cannot be created, most often because a wrong path is entered (for example, for Kubernetes mount, etc,), it cannot be removed.

We created a resource that failed to be created in Vault because of permission problem (we saw 403). Indeed, it was our mistake, but then - the path (and some other fields in the CR cannot be modified, and when we tried to delete the CR, it was stuck in Deleting state and never removed.

The only workaround was to grant priviliges to the wrong path in Vault, resource got created in Vault, and then the CR could be deleted in Opemnshift :-)

**Comment by jfroment** [comment]
+1 for this issue.

@bukovjanmic another workaround is to delete the finalizers on the CR (set metadata.finalizers = []) after a stuck deletion, the resource will be gone for good. This works only if resource creation on Vault was unsuccessful (like permissions problems etc) so it does not leave any resources in Vault.

**Comment by raffaelespazzoli** [comment]
thanks for bringing this up. So perhaps we could do this:
1. add a status field to keep track if the resource was actually ever created in Vault.
2. Upon resource deletion, if the Vault resource was created the finalizer must run, if not the resource can be deleted immediately

**Comment by bukovjanmic** [comment]
Yes, I think this should solve most cases. Also perhaps handle a situation when the resource in Vault does not exist anymore (e.g. deleted in Vault by Vault admin).

And the finalizers workaround could be in documentation for cases where e.g. entire Vault installation is not accessible anymore.
