### ISSUE TITLE
Ansible Automation Platform Support 

### ISSUE THREAD

**Issue by regicsolutions** [redhat-cop/vault-config-operator#253]
Introduce Ansible compatibility by supporting the following CRDs given ansible supports HashiCorp Vault via the [hashi_vault_collection](https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup)

**AnsibleSecretEngineConfig** CRD allows a user to create a Ansible Secret engine configuration.

**AnsibleSecretEngineRole** CRD allows a user to create a Ansible Secret engine role. A role allows to create a project scoped secret.

**Comment by erlisb** [comment]
I am not sure if there is currently an ansible secret engine supported by HashiCorp Vault.
Here you can see a list of secret engines: https://developer.hashicorp.com/vault/docs

What are you referring seems more like the use case of a custom secret engine for ansible: https://developer.hashicorp.com/vault/tutorials/custom-secrets-engine

Did I understood your use case correctly ? 

Thanks.

**Comment by regicsolutions** [comment]
@erlisb I thought a AnsibleEngine was available. Thanks for the links!
