### ISSUE TITLE
RandomSecret should set the ttl in kv secret

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/vault-config-operator#27]

**Comment by trevorbox** [comment]
According to the documentation: https://www.vaultproject.io/docs/secrets/kv/kv-v1#ttls "Unlike other secrets engines, the KV secrets engine does not enforce TTLs for expiration. Instead, the lease_duration is a hint for how often consumers should check back for a new value. If provided a key of ttl, the KV secrets engine will utilize this value as the lease duration"

So ill just set set the "ttl" in the payload request equal to the RefreshPeriod.
