### ISSUE TITLE
Vault Agent Injector | Unable to use different Kubernetes Auth Method

### ISSUE THREAD

**Issue by erlisb** [redhat-cop/vault-config-operator#36]
Hi everyone,

First thing, many thanks for creating/proving this Operator.
Due to the complexity provided by Vault itself, but also automating complex concepts such as Access Management/Tenancy is very hard, such Operator is very helpful to provide Vault as Service to many Customers.

As suggested in the documentation, we would like to provide to each Customer/Team a separate Auth Engine i.e 

Team A : type kubernetes, path : cluster1/team-a-kubernetes
Team B : type kubernetes, path : cluster1/team-b-kubernetes
...

But this doesn't seem to work with how Vault Agent Injector (deployed with Official Helm Chart for OCP), where you can specify there only one Kubernetes Auth Method, as shown be below :

```
injector:
  # True if you want to enable vault agent injection.
  enabled: true

  # Mount Path of the Vault Kubernetes Auth Method.
  authPath: "auth/kubernetes"
```

What maybe could work : 

```
injector:
  # True if you want to enable vault agent injection.
  enabled: true

  # Mount Path of the Vault Kubernetes Auth Method.
  authPath: 
  -  "auth/kubernetes"
  -  "cluster1/team-a-kubernetes"
  -  "cluster1/team-b-kubernetes"
```

Environment : 
- OpenShift 4.9
- HashiCorp Vault Helm Chart : https://github.com/hashicorp/vault-helm
    - name: vault
    - version: 0.19.0
    - appVersion: 1.9.3
    - kubeVersion: ">= 1.14.0-0"
- Vault Config Operator :  0.3.1 provided by Red Hat Community of Practice

I don't know if this is by design or if I am missing something, but I was not able to find anything in the Operator documentation.
Any kind of suggestion would be really helpful.

cc : @raffaelespazzoli 

Many Thanks,
erlis

**Comment by raffaelespazzoli** [comment]
@erlisb So the question here seems to be: how can I have the vault agent injector inject an agent that uses a different login path per tenant. This seems to be more of a question for HashiCorp than for this operator. Anyway from what I can see in the docs this is not possible. However you can use annotations in your deployments to change what the injector does on a per tenant basis: 
https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-annotations .
In particular this one https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-auth-path allows you to customize the path.

**Comment by erlisb** [comment]
Hi @raffaelespazzoli ,

thanks for your reply.
I did as you suggested and it works as expected. I will close this "issue".

For anyone who might come across this, please remember to use a full path in the Vault annotation : 
`vault.hashicorp.com/auth-path: "auth/cluster1/team1"`

and not just the name of the AuthEngineMount :  

`vault.hashicorp.com/auth-path: "cluster1/team1"`


We are planning to use this Operator for productions workloads, and I see a lot of potential behind it in the Vault Community, so I would ask if there a plan for the future to further develop and enhance it with additional Auth Methods i.e LDAP or different Secret Engines i.e Azure/AWS ?

Many thanks,
erlis
