### ISSUE TITLE
[quay-secret-engine] add support for repo level permissions

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/vault-config-operator#42]

**Comment by raffaelespazzoli** [comment]
I see the api filed is there, it wasn't in the examples, so I am not sure if it works.

**Comment by sabre1041** [comment]
Please review the documentation on the plugin itsel

https://github.com/redhat-cop/vault-plugin-secrets-quay#roles

It is a a map. Example can be found [here](https://github.com/redhat-cop/vault-plugin-secrets-quay/blob/main/examples/repositories.json)
