### ISSUE TITLE
Kubernetes V1.24

### ISSUE THREAD

**Issue by klst9498** [redhat-cop/vault-config-operator#59]
Hi,
i had the vault-config-operator running on my cluster (v1.23) and it works like a charm. 

Now we updated our Kubernetes Cluster to v1.24.
In 1.24 secrets are not created by default. See [Kubernetes 1.24+ only](https://learn.hashicorp.com/tutorials/vault/agent-kubernetes)" 
Therefore I created a secret manually as described by hashicorp.

Unfortunately I don't get it running again. The vault-config-operator log tells me:
**"unable to find token secret name for service accountvault-admin/default**

One Hint:
In 1.23 ServiceAccounts have a secrets section. So you can query SA for secrets by parsing that section
in 1.24 ServiceAccounts miss that section. You have to have a look into the Annotation of the Service Account to find the corresponding secret. 

see: [commons.go](https://github.com/redhat-cop/vault-config-operator/blob/f8121865b90b933bbfa4fbde25e4518ce959cc2e/api/v1alpha1/commons.go)

	_var tokenSecretName string
	for _, secretName := range serviceAccount.Secrets {
		if strings.Contains(secretName.Name, "token") {
			tokenSecretName = secretName.Name
			break
		}
	}
	if tokenSecretName == "" {
		return "", errors.New("unable to find token secret name for service account" + kubeNamespace + "/" + serviceAccountName)
	}_

Thanks a lot for your help
Klaus

Additional Info:

apiVersion: v1
kind: Secret
metadata:
  name: default
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: vault-admin 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: default
  namespace: vault-admin
  
---

apiVersion: redhatcop.redhat.io/v1alpha1
kind: AuthEngineMount
metadata:
  name: team-dev-kubernetes
  namespace: vault-admin
spec:
  authentication: 
    path: cluster1-admin
    role: vault-admin
  type: kubernetes
  path: cluster1

**Comment by raffaelespazzoli** [comment]
I have never tested on 1.24. please give some time to take a look at this.

**Comment by klst9498** [comment]
thanks a lot If I can help you please let me know.

**Comment by raffaelespazzoli** [comment]
I created and lightly tested a fix here: https://github.com/raffaelespazzoli/vault-config-operator/tree/fix%2359
would you be able to build this branch and test it in your environment? @klst9498

**Comment by klst9498** [comment]
yes sure I will test you fix and let you know.
Thanks a lot
Klaus
