### ISSUE TITLE
Helm chart installation does not allow for configuration of CERTIFICATE_NAMESPACE/CERTIFICATE_NAME ?

### ISSUE THREAD

**Issue by efenex** [redhat-cop/vault-config-operator#7]
When installing vault-config-operator with the helm chart provided, we end up with a ValidatingWebhookConfiguration and MutatingWebhookConfiguration that refers to $CERTIFICATE_NAMESPACE/$CERTIFICATE_NAME in the cert-manager.io/inject-ca-from annotation. This results in creation of custom resources to fail with:

Error from server (InternalError): error when creating "./test/password-policy.yaml": Internal error occurred: failed calling webhook "mpasswordpolicy.kb.io": Post "https://vault-config-operator-webhook-service.mgmt.svc:443/mutate-redhatcop-redhat-io-v1alpha1-passwordpolicy?timeout=10s": x509: certificate signed by unknown authority

This appears to come from the config/helmchart/cert-manager-ca-injection.yaml which is supposed to be edited with kustomize.

Editing the webhook yaml to refer to the correct namespace and the certificate "serving-cert" enables cert-manager to inject the correct caBundle values and enables us to create the custom resources.

Could this be something that is configured through the helm chart, or should kustomize be run on the helm chart before installation? Neither option is explained in the documentation if applicable.

FYI, the helm chart used is vault-config-operator 0.1.0 directly from https://redhat-cop.github.io/vault-config-operator

**Comment by raffaelespazzoli** [comment]
thanks I will look into it.
