### ISSUE TITLE
govulncheck results

### ISSUE THREAD

**Issue by erlisb** [redhat-cop/vault-config-operator#74]
Hi All,

Recently, the Go Dev Team, has released a [Vulnerability Management System](https://go.dev/blog/vuln)  to support developers scan/analyze their code and fix known vulnerabilities. This System consists in the following components : 

- [Go vulnerability database](https://vuln.go.dev/)
- [govulncheck command](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck)
- [API client](https://pkg.go.dev/golang.org/x/vuln/client) 

Should we consider having these components part of this Operator codebase, at least in the CI/CD workflows ?

Many Thanks,
Erlis

**Comment by raffaelespazzoli** [comment]
I think it would be a good idea.

**Comment by sabre1041** [comment]
We are also looking at incorporating sbom generation using [syft](https://github.com/anchore/syft) and image signing using [cosign](https://github.com/sigstore/cosign)

**Comment by sabre1041** [comment]
@erlisb Would you be able to add an issue in the [github-workflows-operators](https://github.com/redhat-cop/github-workflows-operators) repository?

**Comment by erlisb** [comment]
@sabre1041 done. Closing this,
