### ISSUE TITLE
Support directly specifying username and password for DatabaseSecretEngineConfig

### ISSUE THREAD

**Issue by ameyp** [redhat-cop/vault-config-operator#86]
Vault supports (via the CLI, via Terraform etc.) specifying the username and password directly, it would be great if the CRD did as well instead of requiring them to be provided via a Secret/VaultSecret/RandomSecret. Vault lets users rotate the password after the engine has been configured, and if that is done, the engine config will anyway be out of sync with whatever secret was used to initialize it.

**Comment by ameyp** [comment]
I can submit a PR if this is something you'd like supported too.

**Comment by raffaelespazzoli** [comment]
hello, @ameyp and thanks for your suggestions. I'm against putting the password in the CR directly. I am in favor of supporting rotating the credentials. This feature has been asked before. but it is a purely imperative feature difficult to render in a fully declarative way. Anyway here is my design proposal: Add a new section of the spec with the following:
```yaml
credentialRotation:
  enable: true
  rotationPeriod: 3600
```
this would instruct the operator to rotate the credential every hour.  If the period is not specified the credential is rotate only once at creation.
What do you think?

**Comment by ameyp** [comment]
Sorry for the confusion, I didn't mean that I'm interested in adding a way to rotate credentials. I saw the open issue about it and I agree that it's hard, plus the open question around what to do with the resource after the credentials have been rotated. I only brought it up to point out that putting the password in the CR isn't a security malpractice since users can rotate the credentials after the engine has been configured, making the old one useless.

Could you help me understand your opposition to putting the password in the CR directly?

**Comment by raffaelespazzoli** [comment]
In a gitops world, passwords cannot be on resources or else they would be stored in git. Also it's not true that you can rotate the password, in fact we agree that that feature is missing. 
So you'd have to exit the declarative paradigm and do something imperative to change the password today.
But even when that ability to rotate the password will be available in the operator, I'll still be against putting it in the CR.

**Comment by ameyp** [comment]
Fair enough, thanks for explaining
