### ISSUE TITLE
WebhookConfiguration objects not generated correctly via OLM

### ISSUE THREAD

**Issue by erlisb** [redhat-cop/vault-config-operator#90]
**Describe the bug**
During VCO Operator upgrade via OLM from v0.8.0 to v0.8.4, we are facing the following error : 

`Error "failed calling webhook "msecretenginemount.kb.io": failed to call webhook: Post "[https://vault-config-operator-controller-manager-service.vault-config-operator.svc:443/mutate-redhatcop-redhat-io-v1alpha1-secretenginemount?timeout=10s":](https://vault-config-operator-controller-manager-service.vault-config-operator.svc/mutate-redhatcop-redhat-io-v1alpha1-secretenginemount?timeout=10s%22:) service "vault-config-operator-controller-manager-service" not found" for field "undefined".`

It looks like that when the release is being upgraded to v0.8.4, in both MutatingWebhookConfiguration and ValidatingWebhookConfiguration objects, for each Webhook, the wrong service is generated : 

> $ oc get validatingwebhookconfigurations.admissionregistration.k8s.io -l olm.owner=vault-config-operator.v0.8.4 -ojson | jq .items[].webhooks[].clientConfig.service.name
> "vault-config-operator-controller-manager-service"
> "vault-config-operator-controller-manager-service"
> "vault-config-operator-controller-manager-service"

where the correct service should be as follows : 

> - admissionReviewVersions:
>   - v1
>   - v1beta1
>   clientConfig:
>     service:
>       name: **vault-config-operator-webhook-service**
>       namespace: {{.Release.Namespace}}
>       path: /mutate-redhatcop-redhat-io-v1alpha1-secretenginemount
>   failurePolicy: Fail
>   name: msecretenginemount.kb.io

**To Reproduce**
1. Operator is being updated through the Openshift UI : 

![image](https://user-images.githubusercontent.com/40136986/209149770-e51b96a9-2332-440e-973d-1e2bbd9ca832.png)

Logs during the Operator upgrade : 

![image](https://user-images.githubusercontent.com/40136986/209150227-5a097dbb-0764-4368-ac5d-db7b2d100334.png)

**Expected behavior**
WebhookConfigurations for each webhook are generated with the correct service "vault-config-operator-webhook-service" and webhooks are accessed as follows : 

`curl -k https://vault-config-operator-webhook-service.vault-config-operator.svc/mutate-redhatcop-redhat-io-v1alpha1-secretenginemount?timeout=10s`

**Environment**
* Openshift 4.11
  * OLM :  0.19.0
* Kubernetes: 1.24
* Operator release: v0.8.4

@sabre1041 @raffaelespazzoli  can you please check ? 

Thank you

**Comment by raffaelespazzoli** [comment]
please see if removing the operator and reinstalling from scratch fixes the issue. Unfortunately we don't have the resources to test upgrades. But clean installs seem to be working fine.

**Comment by erlisb** [comment]
would this delete its operands ? i.e SecretEngineMounts ect ?

**Comment by erlisb** [comment]
Hi @raffaelespazzoli, fresh installation works fine, but the issue still persists when upgrading from one release to the other i.e v0.8.4 -> v0.8.5

I will close this issue for the moment. We will do some more investigation in our own.

Thnx.
