### ISSUE TITLE
http: TLS handshake error from 10.42.0.0:45928: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by ameyp** [redhat-cop/vault-config-operator#91]
I've deployed the operator to bare metal kubernetes (k3s version 1.24.8) using the helm chart, with `enableCertManager` set to `false` (as default). I've generated my own certs using a self-signed ClusterIssuer, and named the corresponding secrets `webhook-server-cert` and `vault-config-operator-certs`.

The pod spins up correctly, but when I create a custom resource (say, `Policy`), the creation fails with:

```
Error from server (InternalError): error when creating "test-policy.yaml": Internal error occurred: failed calling webhook "mpolicy.kb.io": failed to call webhook: Post "https://vault-config-operator-webhook-service.vault.svc:443/mutate-redhatcop-redhat-io-v1alpha1-policy?timeout=10s": x509: certificate signed by unknown authority
```

And I see the following error in `vault-config-operator`'s logs:

```
http: TLS handshake error from 10.42.0.0:45928: remote error: tls: bad certificate
```

My guess is that this is somehow due to the cert being self-signed? What's confusing to me, is that setting `enableCertManager` to `true` also creates self-signed certs, and that is presumably working?

**Comment by ameyp** [comment]
I tried changing my certificate's name to `serving-cert`, same error.

**Comment by raffaelespazzoli** [comment]
we should add documentation for BYO certs use case. This is a use case that we don't cover because when you install with OLM, this is taken care for. When you install via helm, we assume the presence of cert-manager. A contribution on the docs on this would be welcome.

**Comment by raffaelespazzoli** [comment]
can we close this?

**Comment by ameyp** [comment]
Once the linked PR is merged I think
