### ISSUE TITLE
Cannot delete a RandomSecret

### ISSUE THREAD

**Issue by MrLuje** [redhat-cop/vault-config-operator#92]
I am currently testing this operator to manage some of our workflows and it looks awesome !

I am creating & deleting the below yaml to test my policies :
* setup a KV v2 mount
* create a secret in this mount with a `RandomSecret`
* create a k8s secret with `VaultSecret`

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: kv
  namespace: geocoding-dev
spec:
  authentication:
    path: k8s/o2sm-kubernetes
    role: o2sm-secret-engine-admin
  config:
    defaultLeaseTTL: ""
    forceNoCache: false
    listingVisibility: hidden
    maxLeaseTTL: ""
  options:
    version: "2"
  type: kv
  path: k8s/o2sm
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  namespace: geocoding-dev
  name: geocoding
spec:
  authentication:
    path: k8s/o2sm-kubernetes
    role: o2sm-secret-engine-admin
  isKVSecretsEngineV2: true
  path: k8s/o2sm/kv/data
  secretKey: password
  secretFormat:
    passwordPolicyName: database_policy
  refreshPeriod: 1h
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: database-geocoding
  namespace: geocoding-dev
spec:
  vaultSecretDefinitions:
    - authentication:
        path: k8s/o2sm-kubernetes
        role: o2sm-secret-engine-admin
      name: database-geocoding
      path: k8s/o2sm/kv/data/geocoding
  output:
    name: database-geocoding2
    stringData:
      password: '{{ index . "database-geocoding" "password" }}'
    type: Opaque
    annotations:
      refresh: every-minute
  refreshPeriod: 3m0s
```

Everything works fine from a Vault perspective (creation & deletion) but I'm left with the `RandomSecret` in k8s.
The object have the correct properties set and no errors in **describe** section :
```
deletionGracePeriodSeconds: 0
deletionTimestamp: "2022-12-29T15:40:43Z"
```

In operator logs, I see the SecretEngine & VaultSecret logs but nothing for RandomSecret
```logs
2022-12-29T15:40:43.208781957Z 1.6723284432085931e+09    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/validate-redhatcop-redhat-io-v1alpha1-secretenginemount", "UID": "64ed7231-853c-4a0f-859c-4cf66c974f79", "kind": "redhatcop.redhat.io/v1alpha1, Kind=SecretEngineMount", "resource": {"group":"redhatcop.redhat.io","version":"v1alpha1","resource":"secretenginemounts"}}
2022-12-29T15:40:43.209019439Z 1.672328443208945e+09    INFO    secretenginemount-resource    validate update    {"name": "kv"}
2022-12-29T15:40:43.209189195Z 1.672328443209107e+09    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/validate-redhatcop-redhat-io-v1alpha1-secretenginemount", "code": 200, "reason": "", "UID": "64ed7231-853c-4a0f-859c-4cf66c974f79", "allowed": true}
2022-12-29T15:40:43.237149308Z 1.672328443237007e+09    DEBUG    controllers.VaultSecret    Delete Event    {"kind": "VaultSecret", "namespacedName": "geocoding-dev/database-geocoding"}
2022-12-29T15:40:43.248093813Z 1.672328443247921e+09    DEBUG    controllers.VaultSecret    Delete Event    {"kind": "Secret", "namespacedName": "geocoding-dev/database-geocoding2"}
```

Also quick question, what are the expected semantics of `RandomSecret` ? is it a one-shot generation only ? will it try to regenerate a secret in Vault if its deleted there ?

Thanks

**Comment by raffaelespazzoli** [comment]
not sure why the random secret is not getting deleted. In theory it should be deleted after ensuring that the corresponding secret in vault is also deleted.
Random secret works in two ways: once only secret generation, or periodic secret generation (that is the case in your example). Either way, the controller has no way of knowing if anything changes on the Vault side.
I think all controllers wake up every 6 hours by default, so any configuration divergence should be reconciled at least with that frequency.

**Comment by MrLuje** [comment]
Thanks

> not sure why the random secret is not getting deleted. In theory it should be deleted after ensuring that the corresponding secret in vault is also deleted.

Any simple way to debug this ? I'm open to making changes and deploying a custom version more verbose.
What is the expected flow of RandomSecret deletion ?
* api/v1alpha1/randomsecret_webhook.go
* controllers/randomsecret_controller.go

**Comment by raffaelespazzoli** [comment]
please look at #93 to see if you are in the same situation, Also I just pushed a fixed to it, which might help you case too.

**Comment by MrLuje** [comment]
> please look at #93 to see if you are in the same situation, Also I just pushed a fixed to it, which might help you case too.

No I don't think so, resources are properly created and there is no logs at all
I'll give a shot to the last version

**Comment by MrLuje** [comment]
@raffaelespazzoli Tested with `latest` image and I don't have the issue anymore, thanks 👍
