### ISSUE TITLE
[RFE] Ability o configure multiple Vault instances with the same operator

### ISSUE THREAD

**Issue by aelbarkani** [redhat-cop/vault-config-operator#95]
Hi !
I've seen in this section https://github.com/redhat-cop/vault-config-operator/blob/842f4c2dbe01ee69b56558ce169e3a7aeb97a1ba/docs/auth-section.md how to authenticate to the remote Vault instance. However it seems it's not possible to have two CRs configuring two different Vault instances. Would it be possible to add an "address" field to authentication section ?

**Comment by erlisb** [comment]
Having the possibility of configuring several Vault Instances through this Operator would be a nice feature, but just specifying the "address" field in the authentication section is not enough. Additionally, you need to configure a dedicated k8s auth method for each Vault Instance, that will be used by the operator to create all configuration, as shown here : https://github.com/redhat-cop/vault-config-operator#configure-an-kubernetes-authentication-mount-point

**Comment by raffaelespazzoli** [comment]
This is something i always had in mind but I waited to implement to see if there was actual demand for it. At the moment the operator connects to a single Vault instance configured at the operator level. But we could add an optional section to the CR to define and override the Vault instance. It would look something like this:
```yaml
connection:
  vaultURL: ...
  ca: ...
  skipVerify: true/false
```
this contribution would be welcome.

**Comment by erlisb** [comment]
We also would like to have this feature in our Setup, therefore I also might have a look at this.
